version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: atlantico-fullstack-challenge
    container_name: atlantico-fullstack-challenge
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:8000"
    volumes:
      - .env.example/:/var/www/.env
    networks:
      - atlantico-fullstack-challenge-net
    command: "scripts/start.sh"
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - atlantico-fullstack-challenge-net

networks:
  atlantico-fullstack-challenge-net:
    driver: bridge
